# Dockerfile.dev
FROM node:20

WORKDIR /app

# Install dependencies before copying code
COPY package*.json ./
RUN npm install

# Copy the rest of your source
COPY . .

# Expose dev server port
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]