# Dockerfile.dev
FROM node:20

WORKDIR /app

# Install dependencies before copying code
COPY package*.json ./

COPY . .

RUN npm install

# Expose dev server port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]