version: '3.9'
services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - dev_nodemods:/app/node_modules
    environment:
      - HOST=0.0.0.0
    command: >
      sh -lc 'if [ ! -d node_modules ] || [ -z "$$(ls -A node_modules 2>/dev/null)" ]; then
        npm ci --include=optional;
      fi && npx svelte-kit sync && npm run dev -- --host'
volumes:
  dev_nodemods:

